"""Dataclasses for local simulation broker and paper ledger."""

from dataclasses import asdict, dataclass

ORDER_ACCEPTED = "ACCEPTED"
ORDER_REJECTED = "REJECTED"
ORDER_FILLED = "FILLED"


@dataclass(frozen=True)
class SimulatedOrder:
    """Order record generated by the local simulation broker."""

    order_id: str
    symbol: str
    side: str
    quantity: float
    requested_quantity: float
    price: float
    fill_price: float | None
    status: str
    timestamp: str
    strategy_id: str | None
    risk_status: str
    risk_reasons: list[str]


@dataclass(frozen=True)
class SimulatedPosition:
    """Current local simulated position."""

    symbol: str
    quantity: float
    average_price: float
    market_price: float | None = None


@dataclass(frozen=True)
class SimulatedAccount:
    """Current local simulated account state."""

    equity: float
    cash: float
    market_value: float
    daily_pnl: float = 0.0
    weekly_pnl: float = 0.0


def order_to_dict(order: SimulatedOrder) -> dict:
    """Convert a simulated order to a dictionary."""
    return asdict(order)


def position_to_dict(position: SimulatedPosition) -> dict:
    """Convert a simulated position to a dictionary."""
    return asdict(position)


def account_to_dict(account: SimulatedAccount) -> dict:
    """Convert a simulated account to a dictionary."""
    return asdict(account)
