"""Strategy export bundle - packages strategy artifacts for external deployment.

This module is research-only. It creates export bundles containing strategy
code, configuration, and readiness reports. No live trading, no broker calls.
"""

import json
import re
import zipfile
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import importlib.metadata


SECRET_PATTERNS = [
    r'api[_\s]?key["\s:=>]+["\']?[\w-]{20,}',
    r'secret["\s:=>]+["\']?[\w-]{20,}',
    r'password["\s:=>]+["\']?[\w-]{8,}',
    r'token["\s:=>]+["\']?[\w-]{20,}',
    r'bearer\s+[\w-]{20,}',
    r'sk[-][\w]{20,}',
]

ALLOWED_PLACEHOLDERS = [
    r"os\.getenv\(",
    r"os\.environ\.get\(",
    r"${",
    r"{{",
]


@dataclass
class ExportBundle:
    """Export bundle containing strategy artifacts."""

    strategy_name: str
    export_timestamp: str
    files: list[str] = field(default_factory=list)
    manifest: dict[str, Any] = field(default_factory=dict)
    disclaimer: str = ""


class SecretDetectionError(Exception):
    """Raised when potential secrets are detected in strategy file."""
    pass


class StrategyExporter:
    """Export strategy artifacts into a zip bundle.

    This is a research-only exporter. It packages strategy files into
    a zip for external deployment. No live trading, no broker calls.
    """

    DEFAULT_DISCLAIMER = (
        "This strategy was generated by AURORA Trading Research for research and "
        "paper-trading purposes only. AURORA does not provide financial advice. "
        "Any live deployment is at the user's sole risk. Past performance does not guarantee future results."
    )

    def __init__(
        self,
        strategy_name: str,
        artifact_directory: str,
        output_zip_path: str,
        strategy_file_path: str | None = None,
        model_path: str | None = None,
        feature_config_path: str | None = None,
        readiness_report_path: str | None = None,
    ) -> None:
        """Initialize strategy exporter.

        Args:
            strategy_name: Name of the strategy to export.
            artifact_directory: Directory containing research artifacts.
            output_zip_path: Path for the output zip file.
            strategy_file_path: Optional path to strategy Python file.
            model_path: Optional path to serialized model file.
            feature_config_path: Optional path to feature configuration.
            readiness_report_path: Optional path to readiness report.
        """
        self.strategy_name = strategy_name
        self.artifact_directory = Path(artifact_directory)
        self.output_zip_path = Path(output_zip_path)
        self.strategy_file_path = Path(strategy_file_path) if strategy_file_path else None
        self.model_path = Path(model_path) if model_path else None
        self.feature_config_path = Path(feature_config_path) if feature_config_path else None
        self.readiness_report_path = Path(readiness_report_path) if readiness_report_path else None

    def _get_version(self) -> str:
        """Get AURORA version."""
        try:
            return importlib.metadata.version("aurora-trading-research")
        except importlib.metadata.PackageNotFoundError:
            return "0.1.0"

    def _scan_for_secrets(self, file_path: Path) -> None:
        """Scan a file for potential secrets.

        Args:
            file_path: Path to the file to scan.

        Raises:
            SecretDetectionError: If potential secrets are found.
        """
        if not file_path.exists():
            return

        content = file_path.read_text()

        for pattern in SECRET_PATTERNS:
            matches = re.findall(pattern, content, re.IGNORECASE)
            if matches:
                for match in matches:
                    if not any(placeholder in match for placeholder in ALLOWED_PLACEHOLDERS):
                        raise SecretDetectionError(
                            f"Potential secret detected in {file_path.name}: "
                            f"found pattern matching '{pattern}'. "
                            "Please remove secrets or use environment variable placeholders."
                        )

    def _find_default_files(self) -> dict[str, Path | None]:
        """Find default-located files in artifact directory.

        Returns:
            Dict mapping file types to paths (or None if not found).
        """
        files = {}

        strategy_search_paths = [
            self.artifact_directory / "strategies" / f"{self.strategy_name}.py",
            self.artifact_directory / f"{self.strategy_name}.py",
        ]
        files["strategy"] = next((p for p in strategy_search_paths if p.exists()), None)

        model_search_paths = [
            self.artifact_directory / "models" / f"{self.strategy_name}.pkl",
            self.artifact_directory / "models" / f"{self.strategy_name}.joblib",
            self.artifact_directory / f"{self.strategy_name}.pkl",
        ]
        files["model"] = next((p for p in model_search_paths if p.exists()), None)

        feature_search_paths = [
            self.artifact_directory / "features" / "feature_config.json",
            self.artifact_directory / "feature_config.json",
        ]
        files["feature_config"] = next((p for p in feature_search_paths if p.exists()), None)

        report_search_paths = [
            self.artifact_directory.parent / "reports" / "readiness_report.json",
            self.artifact_directory / "readiness_report.json",
        ]
        files["readiness_report"] = next((p for p in report_search_paths if p.exists()), None)

        backtest_search = list(self.artifact_directory.glob("*_backtest.json"))
        if backtest_search:
            files["backtest"] = backtest_search[-1]
        else:
            files["backtest"] = None

        diagnostics_search = list(self.artifact_directory.glob("*_diagnostics.json"))
        if diagnostics_search:
            files["diagnostics"] = diagnostics_search[-1]
        else:
            files["diagnostics"] = None

        return files

    def create_bundle(self) -> ExportBundle:
        """Create the export bundle.

        Returns:
            ExportBundle with manifest and file list.

        Raises:
            SecretDetectionError: If secrets are detected in strategy file.
        """
        default_files = self._find_default_files()

        files_to_bundle = []
        warnings = []

        if self.strategy_file_path and self.strategy_file_path.exists():
            self._scan_for_secrets(self.strategy_file_path)
            files_to_bundle.append(("strategy.py", self.strategy_file_path))
        elif default_files.get("strategy"):
            strategy_file = default_files["strategy"]
            self._scan_for_secrets(strategy_file)
            files_to_bundle.append(("strategy.py", strategy_file))
        else:
            warnings.append("Strategy file not found")

        if self.model_path and self.model_path.exists():
            files_to_bundle.append(("model.pkl", self.model_path))
        elif default_files.get("model"):
            files_to_bundle.append(("model.pkl", default_files["model"]))
        else:
            warnings.append("Model file not found (optional)")

        if self.feature_config_path and self.feature_config_path.exists():
            files_to_bundle.append(("feature_config.json", self.feature_config_path))
        elif default_files.get("feature_config"):
            files_to_bundle.append(("feature_config.json", default_files["feature_config"]))
        else:
            warnings.append("Feature config not found (optional)")

        if self.readiness_report_path and self.readiness_report_path.exists():
            files_to_bundle.append(("readiness_report.json", self.readiness_report_path))
        elif default_files.get("readiness_report"):
            files_to_bundle.append(("readiness_report.json", default_files["readiness_report"]))
        else:
            warnings.append("Readiness report not found (optional)")

        if default_files.get("backtest"):
            files_to_bundle.append(("backtest.json", default_files["backtest"]))

        if default_files.get("diagnostics"):
            files_to_bundle.append(("diagnostics.json", default_files["diagnostics"]))

        for warning in warnings:
            print(f"[yellow]Warning:[/yellow] {warning}")

        manifest = {
            "strategy_name": self.strategy_name,
            "export_timestamp": datetime.now(UTC).isoformat(),
            "aurora_version": self._get_version(),
            "files": [
                {"path": dest, "description": self._get_file_description(dest)}
                for dest, _ in files_to_bundle
            ],
            "disclaimer": self.DEFAULT_DISCLAIMER,
        }

        self.output_zip_path.parent.mkdir(parents=True, exist_ok=True)

        with zipfile.ZipFile(self.output_zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for dest, source in files_to_bundle:
                zf.write(source, dest)

            zf.writestr("manifest.json", json.dumps(manifest, indent=2))

        bundle = ExportBundle(
            strategy_name=self.strategy_name,
            export_timestamp=manifest["export_timestamp"],
            files=[dest for dest, _ in files_to_bundle],
            manifest=manifest,
            disclaimer=self.DEFAULT_DISCLAIMER,
        )

        return bundle

    def _get_file_description(self, filename: str) -> str:
        """Get description for a file in the bundle."""
        descriptions = {
            "strategy.py": "Strategy Python source code",
            "model.pkl": "Serialized machine learning model",
            "feature_config.json": "Feature engineering configuration",
            "readiness_report.json": "Comprehensive readiness assessment report",
            "backtest.json": "Historical backtest performance metrics",
            "diagnostics.json": "Walk-forward diagnostics results",
        }
        return descriptions.get(filename, "Additional artifact")

    def verify_bundle(self, zip_path: str | None = None) -> bool:
        """Verify the bundle contents.

        Args:
            zip_path: Path to the zip file. Uses self.output_zip_path if not provided.

        Returns:
            True if bundle is valid, False otherwise.
        """
        path = Path(zip_path or self.output_zip_path)

        if not path.exists():
            return False

        try:
            with zipfile.ZipFile(path, "r") as zf:
                if "manifest.json" not in zf.namelist():
                    return False

                manifest_data = json.loads(zf.read("manifest.json"))

                required_fields = ["strategy_name", "export_timestamp", "aurora_version", "files", "disclaimer"]
                if not all(field in manifest_data for field in required_fields):
                    return False

                bundled_files = set(zf.namelist()) - {"manifest.json"}
                declared_files = {f["path"] for f in manifest_data.get("files", [])}

                if bundled_files != declared_files:
                    return False

            return True

        except (zipfile.BadZipFile, json.JSONDecodeError, KeyError):
            return False