"""Reporting package."""

from aurora.reporting.artifact_packet import (
    ARTIFACT_PACKET_BLOCKED,
    ARTIFACT_PACKET_COMPLETE,
    ARTIFACT_PACKET_PARTIAL,
    PACKET_CRITICAL,
    PACKET_INFO,
    PACKET_WARNING,
    ArtifactPacketConfig,
    ArtifactPacketError,
    ArtifactPacketFinding,
    ArtifactPacketResult,
    artifact_packet_result_to_dict,
    build_artifact_packet,
    save_artifact_packet_manifest,
)
from aurora.reporting.charts import (
    drawdown_chart_data,
    equity_curve_chart_data,
    trade_pnl_chart_data,
)
from aurora.reporting.exceptions import AuroraReportingError, ReportLoadError, ReportSaveError
from aurora.reporting.reports import (
    generate_daily_summary_report,
    load_json_report,
    save_json_report,
    save_markdown_report,
)
from aurora.reporting.summaries import (
    summarize_backtest_metrics,
    summarize_dataframe,
    summarize_orders,
    summarize_positions,
    summarize_risk_decisions,
)
from aurora.reporting.safety_audit import (
    SAFETY_AUDIT_FAIL,
    SAFETY_AUDIT_PASS,
    SAFETY_AUDIT_WARN,
    AUDIT_CRITICAL,
    AUDIT_WARNING,
    SafetyAuditConfig,
    SafetyAuditError,
    SafetyAuditFinding,
    SafetyAuditResult,
    render_safety_audit_markdown,
    run_safety_boundary_audit,
    safety_audit_result_to_dict,
    save_safety_audit_json,
)
from aurora.reporting.status_snapshot import (
    ProjectStatusSnapshotConfig,
    ProjectStatusSnapshotResult,
    create_project_status_snapshot,
    project_status_snapshot_result_to_dict,
    render_project_status_markdown,
    save_project_status_snapshot_json,
)

__all__ = [
    "ARTIFACT_PACKET_BLOCKED",
    "ARTIFACT_PACKET_COMPLETE",
    "ARTIFACT_PACKET_PARTIAL",
    "AUDIT_CRITICAL",
    "AUDIT_WARNING",
    "AuroraReportingError",
    "ArtifactPacketConfig",
    "ArtifactPacketError",
    "ArtifactPacketFinding",
    "ArtifactPacketResult",
    "PACKET_CRITICAL",
    "PACKET_INFO",
    "PACKET_WARNING",
    "ProjectStatusSnapshotConfig",
    "ProjectStatusSnapshotResult",
    "ReportLoadError",
    "ReportSaveError",
    "SAFETY_AUDIT_FAIL",
    "SAFETY_AUDIT_PASS",
    "SAFETY_AUDIT_WARN",
    "SafetyAuditConfig",
    "SafetyAuditError",
    "SafetyAuditFinding",
    "SafetyAuditResult",
    "artifact_packet_result_to_dict",
    "build_artifact_packet",
    "create_project_status_snapshot",
    "drawdown_chart_data",
    "equity_curve_chart_data",
    "generate_daily_summary_report",
    "load_json_report",
    "project_status_snapshot_result_to_dict",
    "render_safety_audit_markdown",
    "render_project_status_markdown",
    "run_safety_boundary_audit",
    "save_artifact_packet_manifest",
    "save_json_report",
    "save_markdown_report",
    "save_project_status_snapshot_json",
    "safety_audit_result_to_dict",
    "save_safety_audit_json",
    "summarize_backtest_metrics",
    "summarize_dataframe",
    "summarize_orders",
    "summarize_positions",
    "summarize_risk_decisions",
    "trade_pnl_chart_data",
]
